repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # v6.0.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: cb8c523fd4835aba42af70f4cad5568db4df0b6c  # v0.16.0
    hooks:
      - id: ruff-check
      - id: ruff-format

  - repo: https://github.com/pycqa/isort
    rev: a333737ed43df02b18e6c95477ea1b285b3de15a  # 8.0.1
    hooks:
      - id: isort

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: d600c142bb19f521ae6a6a345f94a2efd7937759  # v2.26.0
    hooks:
      - id: pyproject-fmt
