repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # v6.0.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 1f1e8bf348ff38fc88619a38d3ca4d9c56abea49  # v0.16.5
    hooks:
      - id: ruff-check
      - id: ruff-format

  - repo: https://github.com/pycqa/isort
    rev: 131f4adcd5582bfc53928ab0d740eceb8b506b6c  # 9.0.1
    hooks:
      - id: isort

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: 3b42b9776870badc9eaffdef9a4a0834b764d87c  # v2.29.3
    hooks:
      - id: pyproject-fmt
