repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # v6.0.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: c59bba8fb259db0fec2bbb77ad8ba51ea7341b56  # v0.15.20
    hooks:
      - id: ruff-check
      - id: ruff-format

  - repo: https://github.com/pycqa/isort
    rev: a333737ed43df02b18e6c95477ea1b285b3de15a  # 8.0.1
    hooks:
      - id: isort

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: 0c8c15d8fe996493035be407c5cf4a288cf6bf8e  # v2.25.1
    hooks:
      - id: pyproject-fmt
